name: osdf-cookbook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - aiohttp
  - bash_kernel
  - intake=0.7.0
  - intake-esm=2024.2.6
  - pelicanplatform
  - panel
  - bokeh
  - xmltodict
  - colorcet
  - boto3
  - basemap
  - pelicanfs=1.2.1
  - matplotlib
  - pandas
  - xarray
  - geopandas
  - pystac-client
  - rasterio
  - dask
  - dask-jobqueue
  - pip
  - hvplot
  - plotly
  - zarr
  - s3fs
  - seaborn
  - tqdm
  - h5netcdf
  - import-ipynb
  - pip:
      - OpenVisus
      - openvisuspy
      - igwn-auth-utils==1.4.0

