name: osdf-cookbook
channels:
  - conda-forge
dependencies:
  - python=3.12
  - jupyterlab
  - mystmd
  - jupyterlab-myst
  - aiohttp
  - bash_kernel
  - intake=0.7.0
  - intake-esm=2024.2.6
  - pelicanplatform
  - panel
  - bokeh
  - xmltodict
  - cartopy
  - colorcet
  - cf-units
  - boto3
  - basemap
  - pelicanfs=1.2.1
  - matplotlib
  - metpy
  - pandas
  - xarray
  - geopandas
  - pystac-client
  - rasterio
  - dask
  - dask-jobqueue
  - pip
  - openpyxl
  - hvplot
  - plotly
  - zarr=2.18.1
  - s3fs
  - seaborn
  - tqdm
  - h5netcdf
  - igwn-auth-utils=1.4.0
  - pip:
      - import-ipynb
      - OpenVisus
      - openvisuspy
      - pvlib
      - rioxarray
